// src/themes/themes.js

export const THEMES = [
  {
    id: 'midnight-ink',
    name: 'Midnight Ink',
    description: 'Deep navy + electric indigo',
    swatchColors: ['#0f172a', '#6366f1', '#e8a045'],
    vars: {
      '--color-background-primary':   '#ffffff',
      '--color-background-secondary': '#f1f5f9',
      '--color-background-tertiary':  '#f8f9fc',
      '--color-text-primary':         '#0f172a',
      '--color-text-secondary':       '#475569',
      '--color-text-tertiary':        '#94a3b8',
      '--color-border-tertiary':      'rgba(15,23,42,0.08)',
      '--color-border-secondary':     'rgba(15,23,42,0.14)',
      '--color-border-primary':       'rgba(15,23,42,0.22)',
      '--accent':                     '#6366f1',
      '--accent-bg':                  '#eef2ff',
      '--accent-text':                '#4338ca',
      '--gold':                       '#e8a045',
      '--gold-bg':                    '#fdf4e7',
      '--green':                      '#2a7a4b',
      '--green-bg':                   '#edf7f1',
      '--red':                        '#b83232',
      '--red-bg':                     '#fdf0f0',
      '--amber':                      '#a06020',
      '--amber-bg':                   '#fdf6e7',
      '--teal':                       '#1a6b6b',
      '--teal-bg':                    '#eaf6f6',
      '--s-applied-bg':               '#dbeafe',
      '--s-applied-text':             '#1e40af',
      '--s-review-bg':                '#ede9fe',
      '--s-review-text':              '#5b21b6',
      '--s-shortlisted-bg':           '#fef3c7',
      '--s-shortlisted-text':         '#92400e',
      '--s-interview-bg':             '#cffafe',
      '--s-interview-text':           '#155e75',
      '--s-selected-bg':              '#dcfce7',
      '--s-selected-text':            '#166534',
      '--s-rejected-bg':              '#fee2e2',
      '--s-rejected-text':            '#991b1b',
      '--border-radius-md':           '8px',
      '--border-radius-lg':           '12px',
      '--border-radius-xl':           '16px',
      // Legacy alias for existing design-system
      '--color-background-warning':   '#fefce8',
      '--color-text-warning':         '#ca8a04',
      '--color-background-danger':    '#fef2f2',
      '--color-text-danger':          '#dc2626',
    },
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'True dark + violet glow',
    swatchColors: ['#09090b', '#7c3aed', '#f59e0b'],
    vars: {
      '--color-background-primary':   '#18181b',
      '--color-background-secondary': '#27272a',
      '--color-background-tertiary':  '#09090b',
      '--color-text-primary':         '#fafafa',
      '--color-text-secondary':       '#a1a1aa',
      '--color-text-tertiary':        '#52525b',
      '--color-border-tertiary':      'rgba(255,255,255,0.07)',
      '--color-border-secondary':     'rgba(255,255,255,0.13)',
      '--color-border-primary':       'rgba(255,255,255,0.20)',
      '--accent':                     '#7c3aed',
      '--accent-bg':                  '#1e1030',
      '--accent-text':                '#a78bfa',
      '--gold':                       '#f59e0b',
      '--gold-bg':                    '#2d1f00',
      '--green':                      '#4ade80',
      '--green-bg':                   '#052e16',
      '--red':                        '#f87171',
      '--red-bg':                     '#450a0a',
      '--amber':                      '#fcd34d',
      '--amber-bg':                   '#451a03',
      '--teal':                       '#5eead4',
      '--teal-bg':                    '#042f2e',
      '--s-applied-bg':               '#1e3a5f',
      '--s-applied-text':             '#93c5fd',
      '--s-review-bg':                '#2e1065',
      '--s-review-text':              '#c4b5fd',
      '--s-shortlisted-bg':           '#451a03',
      '--s-shortlisted-text':         '#fcd34d',
      '--s-interview-bg':             '#042f2e',
      '--s-interview-text':           '#5eead4',
      '--s-selected-bg':              '#052e16',
      '--s-selected-text':            '#86efac',
      '--s-rejected-bg':              '#450a0a',
      '--s-rejected-text':            '#fca5a5',
      '--border-radius-md':           '8px',
      '--border-radius-lg':           '12px',
      '--border-radius-xl':           '16px',
      '--color-background-warning':   '#2d1f00',
      '--color-text-warning':         '#fcd34d',
      '--color-background-danger':    '#450a0a',
      '--color-text-danger':          '#f87171',
    },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Warm cream + emerald',
    swatchColors: ['#1c1917', '#059669', '#e8a045'],
    vars: {
      '--color-background-primary':   '#ffffff',
      '--color-background-secondary': '#f5f4f0',
      '--color-background-tertiary':  '#faf9f7',
      '--color-text-primary':         '#1c1917',
      '--color-text-secondary':       '#57534e',
      '--color-text-tertiary':        '#a8a29e',
      '--color-border-tertiary':      'rgba(28,25,23,0.08)',
      '--color-border-secondary':     'rgba(28,25,23,0.14)',
      '--color-border-primary':       'rgba(28,25,23,0.22)',
      '--accent':                     '#059669',
      '--accent-bg':                  '#ecfdf5',
      '--accent-text':                '#065f46',
      '--gold':                       '#e8a045',
      '--gold-bg':                    '#fdf4e7',
      '--green':                      '#2a7a4b',
      '--green-bg':                   '#edf7f1',
      '--red':                        '#b83232',
      '--red-bg':                     '#fdf0f0',
      '--amber':                      '#a06020',
      '--amber-bg':                   '#fdf6e7',
      '--teal':                       '#0f766e',
      '--teal-bg':                    '#ccfbf1',
      '--s-applied-bg':               '#dbeafe',
      '--s-applied-text':             '#1e40af',
      '--s-review-bg':                '#ede9fe',
      '--s-review-text':              '#5b21b6',
      '--s-shortlisted-bg':           '#fef3c7',
      '--s-shortlisted-text':         '#92400e',
      '--s-interview-bg':             '#ccfbf1',
      '--s-interview-text':           '#0f766e',
      '--s-selected-bg':              '#dcfce7',
      '--s-selected-text':            '#166534',
      '--s-rejected-bg':              '#fee2e2',
      '--s-rejected-text':            '#991b1b',
      '--border-radius-md':           '8px',
      '--border-radius-lg':           '12px',
      '--border-radius-xl':           '16px',
      '--color-background-warning':   '#fefce8',
      '--color-text-warning':         '#ca8a04',
      '--color-background-danger':    '#fef2f2',
      '--color-text-danger':          '#dc2626',
    },
  },
  {
    id: 'slate-pro',
    name: 'Slate Pro',
    description: 'Cool gray + cyan punch',
    swatchColors: ['#0f1729', '#06b6d4', '#e8a045'],
    vars: {
      '--color-background-primary':   '#ffffff',
      '--color-background-secondary': '#f0f4f8',
      '--color-background-tertiary':  '#e8eef4',
      '--color-text-primary':         '#0f1729',
      '--color-text-secondary':       '#4a5568',
      '--color-text-tertiary':        '#90a0b4',
      '--color-border-tertiary':      'rgba(15,23,42,0.09)',
      '--color-border-secondary':     'rgba(15,23,42,0.15)',
      '--color-border-primary':       'rgba(15,23,42,0.23)',
      '--accent':                     '#06b6d4',
      '--accent-bg':                  '#ecfeff',
      '--accent-text':                '#0e7490',
      '--gold':                       '#e8a045',
      '--gold-bg':                    '#fdf4e7',
      '--green':                      '#2a7a4b',
      '--green-bg':                   '#edf7f1',
      '--red':                        '#b83232',
      '--red-bg':                     '#fdf0f0',
      '--amber':                      '#a06020',
      '--amber-bg':                   '#fdf6e7',
      '--teal':                       '#0e7490',
      '--teal-bg':                    '#cffafe',
      '--s-applied-bg':               '#dbeafe',
      '--s-applied-text':             '#1e40af',
      '--s-review-bg':                '#ede9fe',
      '--s-review-text':              '#5b21b6',
      '--s-shortlisted-bg':           '#fef3c7',
      '--s-shortlisted-text':         '#92400e',
      '--s-interview-bg':             '#cffafe',
      '--s-interview-text':           '#155e75',
      '--s-selected-bg':              '#dcfce7',
      '--s-selected-text':            '#166534',
      '--s-rejected-bg':              '#fee2e2',
      '--s-rejected-text':            '#991b1b',
      '--border-radius-md':           '8px',
      '--border-radius-lg':           '12px',
      '--border-radius-xl':           '16px',
      '--color-background-warning':   '#fefce8',
      '--color-text-warning':         '#ca8a04',
      '--color-background-danger':    '#fef2f2',
      '--color-text-danger':          '#dc2626',
    },
  },
  {
    id: 'rosewood',
    name: 'Rosewood',
    description: 'Dusty rose + charcoal',
    swatchColors: ['#1a0e0e', '#e11d48', '#f97316'],
    vars: {
      '--color-background-primary':   '#ffffff',
      '--color-background-secondary': '#fdf2f2',
      '--color-background-tertiary':  '#fdf8f8',
      '--color-text-primary':         '#1a0e0e',
      '--color-text-secondary':       '#6b4f4f',
      '--color-text-tertiary':        '#b08a8a',
      '--color-border-tertiary':      'rgba(26,14,14,0.08)',
      '--color-border-secondary':     'rgba(26,14,14,0.14)',
      '--color-border-primary':       'rgba(26,14,14,0.22)',
      '--accent':                     '#e11d48',
      '--accent-bg':                  '#fff1f2',
      '--accent-text':                '#9f1239',
      '--gold':                       '#f97316',
      '--gold-bg':                    '#fff7ed',
      '--green':                      '#2a7a4b',
      '--green-bg':                   '#edf7f1',
      '--red':                        '#b83232',
      '--red-bg':                     '#fdf0f0',
      '--amber':                      '#a06020',
      '--amber-bg':                   '#fdf6e7',
      '--teal':                       '#1a6b6b',
      '--teal-bg':                    '#eaf6f6',
      '--s-applied-bg':               '#dbeafe',
      '--s-applied-text':             '#1e40af',
      '--s-review-bg':                '#ede9fe',
      '--s-review-text':              '#5b21b6',
      '--s-shortlisted-bg':           '#fef3c7',
      '--s-shortlisted-text':         '#92400e',
      '--s-interview-bg':             '#cffafe',
      '--s-interview-text':           '#155e75',
      '--s-selected-bg':              '#dcfce7',
      '--s-selected-text':            '#166534',
      '--s-rejected-bg':              '#fee2e2',
      '--s-rejected-text':            '#991b1b',
      '--border-radius-md':           '8px',
      '--border-radius-lg':           '12px',
      '--border-radius-xl':           '16px',
      '--color-background-warning':   '#fff7ed',
      '--color-text-warning':         '#c2410c',
      '--color-background-danger':    '#fdf0f0',
      '--color-text-danger':          '#b83232',
    },
  },
  {
    id: 'void',
    name: 'Void',
    description: 'Pure black + acid green',
    swatchColors: ['#000000', '#84cc16', '#facc15'],
    vars: {
      '--color-background-primary':   '#0a0a0a',
      '--color-background-secondary': '#171717',
      '--color-background-tertiary':  '#000000',
      '--color-text-primary':         '#f5f5f5',
      '--color-text-secondary':       '#737373',
      '--color-text-tertiary':        '#404040',
      '--color-border-tertiary':      'rgba(255,255,255,0.06)',
      '--color-border-secondary':     'rgba(255,255,255,0.11)',
      '--color-border-primary':       'rgba(255,255,255,0.18)',
      '--accent':                     '#84cc16',
      '--accent-bg':                  '#0d1a00',
      '--accent-text':                '#bef264',
      '--gold':                       '#facc15',
      '--gold-bg':                    '#1a1500',
      '--green':                      '#86efac',
      '--green-bg':                   '#0a1f00',
      '--red':                        '#fca5a5',
      '--red-bg':                     '#2d0a0a',
      '--amber':                      '#fcd34d',
      '--amber-bg':                   '#2d1500',
      '--teal':                       '#5eead4',
      '--teal-bg':                    '#001a1a',
      '--s-applied-bg':               '#0c1a3d',
      '--s-applied-text':             '#93c5fd',
      '--s-review-bg':                '#1a0d3d',
      '--s-review-text':              '#c4b5fd',
      '--s-shortlisted-bg':           '#2d1500',
      '--s-shortlisted-text':         '#fcd34d',
      '--s-interview-bg':             '#001a1a',
      '--s-interview-text':           '#5eead4',
      '--s-selected-bg':              '#0a1f00',
      '--s-selected-text':            '#86efac',
      '--s-rejected-bg':              '#2d0a0a',
      '--s-rejected-text':            '#fca5a5',
      '--border-radius-md':           '8px',
      '--border-radius-lg':           '12px',
      '--border-radius-xl':           '16px',
      '--color-background-warning':   '#2d1500',
      '--color-text-warning':         '#fcd34d',
      '--color-background-danger':    '#2d0a0a',
      '--color-text-danger':          '#fca5a5',
    },
  },
];

export const DEFAULT_THEME_ID = 'midnight-ink';

export function getThemeById(id) {
  return THEMES.find(t => t.id === id) ?? THEMES[0];
}
